# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    serializer_listener.article:
        class: AppBundle\Serializer\Listener\ArticleListener
        tags:
            - { name: jms_serializer.event_subscriber }
