<?php

namespace UserBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{	
	/* advanced search */
    public function search($searchParam) { 
        extract($searchParam);    
        $qb = $this->createQueryBuilder('d');

        if(!empty($keyword)){ 
            $qb->andWhere('d.username like :keyword or d.nom like :keyword or d.prenom like :keyword or d.email like :keyword or d.tel like :keyword or d.roles like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
        }
        if(!empty($sortBy)){ 
            $sortBy = in_array($sortBy, array('nom')) ? $sortBy : 'id';
            $sortDir = ($sortDir == 'DESC') ? 'DESC' : 'ASC';
            $qb->orderBy('d.' . $sortBy, $sortDir);
        }
        if(!empty($perPage)) $qb->setFirstResult(($page - 1) * $perPage)->setMaxResults($perPage);
       return new Paginator($qb->getQuery());
    }
}
