<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * DestinationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DestinationRepository extends \Doctrine\ORM\EntityRepository
{	
	/* advanced search */
    public function search($searchParam) { 
        extract($searchParam);           
        $qb = $this->createQueryBuilder('d');

        if(!empty($keyword)){ 
            $qb->andWhere('d.nom like :keyword or d.telephone like :keyword or d.email like :keyword or d.adresse like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
        }
        if(!empty($sortBy)){ 
            $sortBy = in_array($sortBy, array('nom')) ? $sortBy : 'id';
            $sortDir = ($sortDir == 'DESC') ? 'DESC' : 'ASC';
            $qb->orderBy('d.' . $sortBy, $sortDir);
        }
        if(!empty($perPage)) $qb->setFirstResult(($page - 1) * $perPage)->setMaxResults($perPage);

       return new Paginator($qb->getQuery());
    }
}
