<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * EntreeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntreeRepository extends \Doctrine\ORM\EntityRepository
{
	/* advanced search */
    public function search($searchParam) { 
        extract($searchParam);           
        $qb = $this->createQueryBuilder('d')
        	->leftJoin('d.produit', 'p')
            ->addSelect('p')
            ->leftJoin('d.utilisation', 'u')
            ->addSelect('u');

        if(!empty($keyword)){
            $qb->andWhere('d.code like :keyword or p.dci like :keyword or d.dosage like :keyword or d.quantite like :keyword or d.conditionnement like :keyword or u.nom like :keyword or d.dateEntree like :keyword or d.datePeremption like :keyword or d.annee like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
        }
        if(!empty($sortBy)){ 
            $sortBy = in_array($sortBy, array('code')) ? $sortBy : 'id';
            $sortDir = ($sortDir == 'DESC') ? 'DESC' : 'ASC';
            $qb->orderBy('d.' . $sortBy, $sortDir);
        }
        if(!empty($perPage)) $qb->setFirstResult(($page - 1) * $perPage)->setMaxResults($perPage);

       return new Paginator($qb->getQuery());
    }
}
