<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * ProduitRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProduitRepository extends \Doctrine\ORM\EntityRepository
{	
	/* advanced search */
    public function search($searchParam) { 
        extract($searchParam);           
        $qb = $this->createQueryBuilder('p')
        	->leftJoin('p.categorie', 'c')
            ->addSelect('c');

        if(!empty($keyword)){ 
            $qb->andWhere('p.code like :keyword or p.dci like :keyword or p.nature like :keyword or c.nom like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
        }
        if(!empty($sortBy)){ 
            $sortBy = in_array($sortBy, array('nom')) ? $sortBy : 'id';
            $sortDir = ($sortDir == 'DESC') ? 'DESC' : 'ASC';
            $qb->orderBy('p.' . $sortBy, $sortDir);
        }
        if(!empty($perPage)) $qb->setFirstResult(($page - 1) * $perPage)->setMaxResults($perPage);

       return new Paginator($qb->getQuery());
    }
}
