<?php

namespace GestionBundle\Repository;

use Doctrine\ORM\Tools\Pagination\Paginator;
/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{	
	/* advanced search */
    public function search($searchParam) { 
        extract($searchParam);           
         $qb = $this->createQueryBuilder('d');

        if(!empty($keyword)){ 
            $qb->andWhere('d.code like :keyword or d.dci like :keyword  or d.dosage like :keyword or d.conditionnement like :keyword or d.utilisation like :keyword or d.quantite like :keyword or d.datePeremption like :keyword')
                ->setParameter('keyword', '%'.$keyword.'%');
        }
        if(!empty($sortBy)){ 
            $sortBy = in_array($sortBy, array('nom')) ? $sortBy : 'id';
            $sortDir = ($sortDir == 'DESC') ? 'DESC' : 'ASC';
            $qb->orderBy('d.' . $sortBy, $sortDir);
        }
        if(!empty($perPage)) $qb->setFirstResult(($page - 1) * $perPage)->setMaxResults($perPage);

       return new Paginator($qb->getQuery());
    }

    /* advanced search */
    public function peremption($query)
    {   
        $q = $this->_em->createQuery($query);
        $results = $q->getResult(); 
        
        return $results;
    }

    public function stockperime()
    {
      $qb = $this->createQueryBuilder('a');

      $qb->where('a.datePeremption < :date')
           ->setParameter('date', new \Datetime())
         ->orderBy('a.id', 'DESC')
      ;

      return $qb->getQuery()->getResult();
    }
}
